title: Zachary's Website
email: zacharylopez@mail.weber.edu
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
logo: "/assets/images/logo.png"
baseurl: "/cs-1030-hadzik-classroom-my-first-website-my_first_website" # the subpath of your site
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
